---

# - name: Update apt-cache
#   apt: update_cache=yes

- name: Download and install haproxy
  apt: name=haproxy state=present

- name: Download and install haproxyctl
  apt: name=haproxyctl state=present

- name: Download and install hatop
  apt: name=hatop state=present

- name: Ensure the service starts automatically each time the server powers on
  lineinfile:
    path: /etc/default/haproxy
    regexp: '^ENABLED='
    line: ENABLED=1

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes