---

all:
  hosts:
  children:
    lbservers:
      hosts:
        proxy1:
          ansible_host: localhost
          ansible_port: 2222
        proxy2:
          ansible_host: localhost
          ansible_port: 2223